export const FINANCE_SEED_RULES: Array<{ match: string; category: string }> = [
  { match: "slash fee: foreign transaction fee for 03.29.26", category: "one_time" },
  { match: "slash fee: foreign transaction fee for 04.02.26", category: "one_time" },
  { match: "slash fee: foreign transaction fee for 04.09.26", category: "one_time" },
  { match: "slash fee: foreign transaction fee for 04.14.26", category: "one_time" },
  { match: "swift transfer from rares catalin daia", category: "revenue" },
  { match: "ezequiel domingo pizarro mirenzi", category: "salary" },
  { match: "portcast media limited (adtiger)", category: "ad_spend" },
  { match: "international wire transfer fee", category: "one_time" },
  { match: "payment from platinum account", category: "internal_transfer" },
  { match: "fairing post purchase surveys", category: "subscription" },
  { match: "trueprofit: profit analytics", category: "subscription" },
  { match: "daily credit card payment", category: "internal_transfer" },
  { match: "slash subscription 01-23", category: "subscription" },
  { match: "slash subscription 02-23", category: "subscription" },
  { match: "slash subscription 03-23", category: "subscription" },
  { match: "slash subscription 10-23", category: "subscription" },
  { match: "slash subscription 11-23", category: "subscription" },
  { match: "slash subscription 12-23", category: "subscription" },
  { match: "google workspace_bluebr", category: "subscription" },
  { match: "linkedin recruiter p875", category: "hr" },
  { match: "claude.ai subscription", category: "subscription" },
  { match: "fc* freepik premium+ m", category: "subscription" },
  { match: "gumroad* craftr by pro", category: "subscription" },
  { match: "dziubakevych khrystyna", category: "salary" },
  { match: "openai *chatgpt subscr", category: "subscription" },
  { match: "swipekit ad inspo tool", category: "subscription" },
  { match: "corporate filings llc", category: "taxes" },
  { match: "intuit *qbooks online", category: "subscription" },
  { match: "klaviyo inc. software", category: "subscription" },
  { match: "quora* temporary hold", category: "subscription" },
  { match: "shopify platform fee", category: "subscription" },
  { match: "darrel shan mallari", category: "salary" },
  { match: "google*cloud 4nngvg", category: "subscription" },
  { match: "google cloud 4zlfkg", category: "subscription" },
  { match: "google cloud 7nmn56", category: "subscription" },
  { match: "google cloud 7ntk3v", category: "subscription" },
  { match: "google cloud 9b8xc2", category: "subscription" },
  { match: "google cloud 9wkt5v", category: "subscription" },
  { match: "google cloud 9wz8vx", category: "subscription" },
  { match: "google cloud bpvttc", category: "subscription" },
  { match: "google cloud hfq34z", category: "subscription" },
  { match: "google cloud nbd82z", category: "subscription" },
  { match: "google cloud nfgst3", category: "subscription" },
  { match: "google cloud px43tz", category: "subscription" },
  { match: "google cloud sprwjj", category: "subscription" },
  { match: "google cloud xzktdz", category: "subscription" },
  { match: "google cloud zk3zv9", category: "subscription" },
  { match: "google cloud vfvw3x", category: "subscription" },
  { match: "google cloud wbs2d4", category: "subscription" },
  { match: "google cloud xcp3fx", category: "subscription" },
  { match: "google cloud zflh2s", category: "subscription" },
  { match: "khrystyna vasylivna", category: "salary" },
  { match: "upwork * -897647741", category: "salary" },
  { match: "upwork * -899801436", category: "salary" },
  { match: "upwork * -901942901", category: "salary" },
  { match: "upwork * -904007040", category: "salary" },
  { match: "upwork * -906129454", category: "salary" },
  { match: "upwork * -908193021", category: "salary" },
  { match: "upwork * -910242774", category: "salary" },
  { match: "facebk *253ffjhdj2", category: "ad_spend" },
  { match: "facebk *257rtghdj2", category: "ad_spend" },
  { match: "facebk *29cn7hddj2", category: "ad_spend" },
  { match: "facebk *2dec7gvcj2", category: "ad_spend" },
  { match: "facebk *2ggggjzcj2", category: "ad_spend" },
  { match: "facebk *373ghgmep2", category: "ad_spend" },
  { match: "facebk *3p8f3gdep2", category: "ad_spend" },
  { match: "facebk *44xq2lddj2", category: "ad_spend" },
  { match: "facebk *47jctg9dj2", category: "ad_spend" },
  { match: "facebk *49lxxgvdj2", category: "ad_spend" },
  { match: "facebk *4jndqg5dj2", category: "ad_spend" },
  { match: "facebk *4pbsjjvep2", category: "ad_spend" },
  { match: "facebk *55stdhrep2", category: "ad_spend" },
  { match: "facebk *5rfs4gmdj2", category: "ad_spend" },
  { match: "facebk *5u9ltg9ep2", category: "ad_spend" },
  { match: "facebk *5vtn7ghdj2", category: "ad_spend" },
  { match: "facebk *64kkjj9dj2", category: "ad_spend" },
  { match: "facebk *66pdsgddj2", category: "ad_spend" },
  { match: "facebk *69d37gzep2", category: "ad_spend" },
  { match: "facebk *6a4z6jhdj2", category: "ad_spend" },
  { match: "facebk *6rxjhg5dj2", category: "ad_spend" },
  { match: "facebk *7rw8bfvcj2", category: "ad_spend" },
  { match: "facebk *7rzs8hhep2", category: "ad_spend" },
  { match: "facebk *7wvq8l5dj2", category: "ad_spend" },
  { match: "facebk *82p32hddj2", category: "ad_spend" },
  { match: "facebk *84e8gnrdj2", category: "ad_spend" },
  { match: "facebk *86e9gl5dj2", category: "ad_spend" },
  { match: "facebk *86r57jddj2", category: "ad_spend" },
  { match: "facebk *88znblrdj2", category: "ad_spend" },
  { match: "facebk *8vur2jhep2", category: "ad_spend" },
  { match: "facebk *92y9qf9dj2", category: "ad_spend" },
  { match: "facebk *99f6mh5dj2", category: "ad_spend" },
  { match: "facebk *9cbxyh5dj2", category: "ad_spend" },
  { match: "facebk *9e3a9gddj2", category: "ad_spend" },
  { match: "facebk *9exxrlhdj2", category: "ad_spend" },
  { match: "facebk *9k8fykvdj2", category: "ad_spend" },
  { match: "facebk *9merugvcj2", category: "ad_spend" },
  { match: "facebk *amg8khhdj2", category: "ad_spend" },
  { match: "facebk *arlchf5dj2", category: "ad_spend" },
  { match: "facebk *axlvckrdj2", category: "ad_spend" },
  { match: "facebk *b4pbqhvdj2", category: "ad_spend" },
  { match: "facebk *bkeekf5dj2", category: "ad_spend" },
  { match: "facebk *blh7ugrep2", category: "ad_spend" },
  { match: "facebk *bm36ghrep2", category: "ad_spend" },
  { match: "facebk *cr7uyg9dj2", category: "ad_spend" },
  { match: "facebk *ege72j9dj2", category: "ad_spend" },
  { match: "facebk *eq8gkgzcj2", category: "ad_spend" },
  { match: "facebk *er7a8gddj2", category: "ad_spend" },
  { match: "facebk *esd4zghdj2", category: "ad_spend" },
  { match: "facebk *euqtdg5dj2", category: "ad_spend" },
  { match: "facebk *evbpdfvcj2", category: "ad_spend" },
  { match: "facebk *ewxr6hzcj2", category: "ad_spend" },
  { match: "facebk *eyk8ggmep2", category: "ad_spend" },
  { match: "facebk *f4ab2h5dj2", category: "ad_spend" },
  { match: "facebk *fe7uvg9dj2", category: "ad_spend" },
  { match: "facebk *fhajmg9dj2", category: "ad_spend" },
  { match: "facebk *fmwwajhdj2", category: "ad_spend" },
  { match: "facebk *g4et7jmdj2", category: "ad_spend" },
  { match: "facebk *g8d75g5fp2", category: "ad_spend" },
  { match: "facebk *gk5u8hhep2", category: "ad_spend" },
  { match: "facebk *hb34dgmdj2", category: "ad_spend" },
  { match: "facebk *hkk8egvcj2", category: "ad_spend" },
  { match: "facebk *hy9aggmdj2", category: "ad_spend" },
  { match: "facebk *jshshkrdj2", category: "ad_spend" },
  { match: "facebk *k5v3kjzcj2", category: "ad_spend" },
  { match: "facebk *kcu64hhdj2", category: "ad_spend" },
  { match: "facebk *kjmn8f5ep2", category: "ad_spend" },
  { match: "facebk *kjrzjf9dj2", category: "ad_spend" },
  { match: "facebk *lchbhf9dj2", category: "ad_spend" },
  { match: "facebk *ldy3wf9dj2", category: "ad_spend" },
  { match: "facebk *lgu3mkrdj2", category: "ad_spend" },
  { match: "facebk *lxubljhdj2", category: "ad_spend" },
  { match: "facebk *mk7clh9ep2", category: "ad_spend" },
  { match: "facebk *mkqktgrep2", category: "ad_spend" },
  { match: "facebk *mvup5kmdj2", category: "ad_spend" },
  { match: "facebk *myt7ggdep2", category: "ad_spend" },
  { match: "facebk *n8dmygzcj2", category: "ad_spend" },
  { match: "facebk *nahfggvdj2", category: "ad_spend" },
  { match: "facebk *nqevyfmdj2", category: "ad_spend" },
  { match: "facebk *nr2calrdj2", category: "ad_spend" },
  { match: "facebk *nz5slmrdj2", category: "ad_spend" },
  { match: "facebk *pf4wdjvcj2", category: "ad_spend" },
  { match: "facebk *pgbudg5fp2", category: "ad_spend" },
  { match: "facebk *pj6swlrep2", category: "ad_spend" },
  { match: "facebk *pumael5fp2", category: "ad_spend" },
  { match: "facebk *pvyarghdj2", category: "ad_spend" },
  { match: "facebk *q7zk9grep2", category: "ad_spend" },
  { match: "facebk *qc4exkrdj2", category: "ad_spend" },
  { match: "facebk *qxpengvdj2", category: "ad_spend" },
  { match: "facebk *rcq54lrdj2", category: "ad_spend" },
  { match: "facebk *sjatgk5dj2", category: "ad_spend" },
  { match: "facebk *snjmyfvdj2", category: "ad_spend" },
  { match: "facebk *t2yxffvcj2", category: "ad_spend" },
  { match: "facebk *t75ddg9dj2", category: "ad_spend" },
  { match: "facebk *tcjfygmdj2", category: "ad_spend" },
  { match: "facebk *tf7xlf5ep2", category: "ad_spend" },
  { match: "facebk *tx8e7h5dj2", category: "ad_spend" },
  { match: "facebk *ue92qhvcj2", category: "ad_spend" },
  { match: "facebk *ugpadkzcj2", category: "ad_spend" },
  { match: "facebk *ugrvnk5dj2", category: "ad_spend" },
  { match: "facebk *ukccbg9dj2", category: "ad_spend" },
  { match: "facebk *uppm5h5dj2", category: "ad_spend" },
  { match: "facebk *uwn95j9dj2", category: "ad_spend" },
  { match: "facebk *v2lfbjzcj2", category: "ad_spend" },
  { match: "facebk *vpcayhvcj2", category: "ad_spend" },
  { match: "facebk *wcaxwg5dj2", category: "ad_spend" },
  { match: "facebk *wjnsejvep2", category: "ad_spend" },
  { match: "facebk *wr99bfvcj2", category: "ad_spend" },
  { match: "facebk *wulcnjvcj2", category: "ad_spend" },
  { match: "facebk *x4x2rfzep2", category: "ad_spend" },
  { match: "facebk *xqzbgjddj2", category: "ad_spend" },
  { match: "facebk *xtq86gmdj2", category: "ad_spend" },
  { match: "facebk *xuneqmrdj2", category: "ad_spend" },
  { match: "facebk *xvjrbj9dj2", category: "ad_spend" },
  { match: "facebk *xzfaxgmdj2", category: "ad_spend" },
  { match: "facebk *y22dsgzcj2", category: "ad_spend" },
  { match: "facebk *ymbzghmep2", category: "ad_spend" },
  { match: "facebk *ymwwtfmdj2", category: "ad_spend" },
  { match: "facebk *ypfw7g9dj2", category: "ad_spend" },
  { match: "facebk *ywyabhhdj2", category: "ad_spend" },
  { match: "facebk *zbtdehvdj2", category: "ad_spend" },
  { match: "facebk *zcrbmgmdj2", category: "ad_spend" },
  { match: "facebk *zgzwxf5ep2", category: "ad_spend" },
  { match: "facebk *zxx4ch9ep2", category: "ad_spend" },
  { match: "facebk *zzlltgrep2", category: "ad_spend" },
  { match: "wassef ben said sg", category: "salary" },
  { match: "shopify* 496458206", category: "subscription" },
  { match: "shopify* 497773751", category: "subscription" },
  { match: "shopify* 498643142", category: "subscription" },
  { match: "shopify* 500571719", category: "subscription" },
  { match: "shopify* 511916886", category: "subscription" },
  { match: "shopify* 512373615", category: "subscription" },
  { match: "shopify* 514261922", category: "subscription" },
  { match: "elevate ab testing", category: "subscription" },
  { match: "charitarth unagar", category: "salary" },
  { match: "slack t0401t2npan", category: "subscription" },
  { match: "www.perplexity.ai", category: "subscription" },
  { match: "jiang jiang long", category: "salary" },
  { match: "sheryll suobiron", category: "salary" },
  { match: "aion manifest co", category: "cogs" },
  { match: "comm of mass eft", category: "taxes" },
  { match: "comp of maryland", category: "taxes" },
  { match: "fla dept revenue", category: "taxes" },
  { match: "happy returns, i", category: "subscription" },
  { match: "il dept of reven", category: "taxes" },
  { match: "mn dept of reven", category: "taxes" },
  { match: "neb dept revenue", category: "taxes" },
  { match: "tn state revenue", category: "taxes" },
  { match: "utah801/297-7703", category: "taxes" },
  { match: "va dept taxation", category: "taxes" },
  { match: "webfile tax pymt", category: "taxes" },
  { match: "shenzhenshixingr", category: "cogs" },
  { match: "one click upsell", category: "subscription" },
  { match: "openai (chatgpt)", category: "subscription" },
  { match: "daniel terekhov", category: "salary" },
  { match: "georgia its tax", category: "taxes" },
  { match: "hawaii dept tax", category: "taxes" },
  { match: "nc dept revenue", category: "taxes" },
  { match: "sc dept revenue", category: "taxes" },
  { match: "wa dept revenue", category: "taxes" },
  { match: "commentguard.io", category: "subscription" },
  { match: "higgsfield inc.", category: "subscription" },
  { match: "sinag marketing", category: "subscription" },
  { match: "ar dfa revenue", category: "taxes" },
  { match: "az dept of rev", category: "taxes" },
  { match: "kentucky doris", category: "taxes" },
  { match: "nv dept of tax", category: "taxes" },
  { match: "apple.com/bill", category: "subscription" },
  { match: "nicolas perez", category: "salary" },
  { match: "8063-1hioosut", category: "subscription" },
  { match: "applovin corp", category: "ad_spend" },
  { match: "elevenlabs.io", category: "subscription" },
  { match: "brahim graoui", category: "salary" },
  { match: "retention.com", category: "subscription" },
  { match: "happy returns", category: "subscription" },
  { match: "naomi cotton", category: "salary" },
  { match: "hubstaff.com", category: "subscription" },
  { match: "daniel jiang", category: "salary" },
  { match: "bryan sibal", category: "salary" },
  { match: "knest slash", category: "salary" },
  { match: "state of ri", category: "taxes" },
  { match: "brandsearch", category: "ad_spend" },
  { match: "vercel inc.", category: "subscription" },
  { match: "wvtreasury", category: "taxes" },
  { match: "chargeflow", category: "subscription" },
  { match: "1password", category: "subscription" },
  { match: "emal safi", category: "salary" },
  { match: "klics llc", category: "salary" },
  { match: "mouss ach", category: "salary" },
  { match: "anthropic", category: "subscription" },
  { match: "route app", category: "subscription" },
  { match: "kevin ma", category: "salary" },
  { match: "manus ai", category: "subscription" },
  { match: "supabase", category: "subscription" },
  { match: "giddyup", category: "affiliate" },
  { match: "shopify", category: "subscription" },
  { match: "lovable", category: "subscription" },
  { match: "netlify", category: "subscription" },
  { match: "todoist", category: "subscription" },
  { match: "capcut", category: "subscription" },
  { match: "elevar", category: "subscription" },
  { match: "envato", category: "subscription" },
  { match: "pluxy", category: "internal_transfer" },
  { match: "rares", category: "salary" },
  { match: "ivan", category: "salary" },
  { match: "jo d", category: "salary" },
  { match: "cdor", category: "taxes" },
  { match: "som", category: "taxes" },
]
