alter table public.performance_brand_day
  add column if not exists product_cogs numeric(14,2) not null default 0,
  add column if not exists shipping_cost numeric(14,2) not null default 0,
  add column if not exists variable_cost numeric(14,2) not null default 0,
  add column if not exists cost_rules_applied jsonb not null default '{}'::jsonb;

update public.performance_brand_day
set
  product_cogs = cogs,
  variable_cost = cogs + shipping_cost
where product_cogs = 0 and cogs <> 0;

create table if not exists public.performance_cost_rules (
  id uuid default gen_random_uuid() primary key,
  brand_slug text not null,
  cost_type text not null check (cost_type in ('product', 'shipping')),
  label text not null,
  status text not null default 'active' check (status in ('active', 'paused')),
  priority integer not null default 100,
  region_key text,
  country_code text,
  province_codes text[] not null default '{}'::text[],
  sku_pattern text,
  title_pattern text,
  variant_pattern text,
  min_kit_quantity integer,
  max_kit_quantity integer,
  kit_multiplier numeric(10,4),
  cartridges_per_kit numeric(10,4),
  dispenser_unit_cost numeric(10,4),
  cartridge_unit_cost numeric(10,4),
  fixed_cost numeric(10,4),
  per_extra_kit_cost numeric(10,4),
  effective_from date,
  effective_to date,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (brand_slug, label)
);

create index if not exists performance_cost_rules_brand_type_idx
  on public.performance_cost_rules (brand_slug, cost_type, status, priority);

alter table public.performance_cost_rules enable row level security;

drop policy if exists "performance_cost_rules_allowed_select" on public.performance_cost_rules;
drop policy if exists "performance_cost_rules_allowed_insert" on public.performance_cost_rules;
drop policy if exists "performance_cost_rules_allowed_update" on public.performance_cost_rules;
drop policy if exists "performance_cost_rules_allowed_delete" on public.performance_cost_rules;

create policy "performance_cost_rules_allowed_select"
on public.performance_cost_rules
for select
to authenticated
using (
  split_part(public.current_request_email(), '@', 1) in ('iskander', 'nicolas', 'naomi')
);

create policy "performance_cost_rules_allowed_insert"
on public.performance_cost_rules
for insert
to authenticated
with check (
  split_part(public.current_request_email(), '@', 1) in ('iskander', 'nicolas', 'naomi')
);

create policy "performance_cost_rules_allowed_update"
on public.performance_cost_rules
for update
to authenticated
using (
  split_part(public.current_request_email(), '@', 1) in ('iskander', 'nicolas', 'naomi')
)
with check (
  split_part(public.current_request_email(), '@', 1) in ('iskander', 'nicolas', 'naomi')
);

create policy "performance_cost_rules_allowed_delete"
on public.performance_cost_rules
for delete
to authenticated
using (
  split_part(public.current_request_email(), '@', 1) in ('iskander', 'nicolas', 'naomi')
);

insert into public.performance_cost_rules (
  brand_slug,
  cost_type,
  label,
  status,
  priority,
  region_key,
  country_code,
  province_codes,
  sku_pattern,
  title_pattern,
  variant_pattern,
  min_kit_quantity,
  max_kit_quantity,
  kit_multiplier,
  cartridges_per_kit,
  dispenser_unit_cost,
  cartridge_unit_cost,
  fixed_cost,
  per_extra_kit_cost,
  effective_from,
  effective_to,
  notes,
  metadata
) values
  (
    'trueclean',
    'product',
    'TrueClean 1-year kit - first 10k cartridge batch',
    'active',
    20,
    null,
    null,
    '{}',
    '^TC-U-SNS-0[1-4]$|^TC-SNS-[A-Z]+-[1-4]$',
    null,
    null,
    null,
    null,
    null,
    4,
    2.50,
    1.00,
    0,
    null,
    null,
    '2026-05-02',
    'Old 1-year kit: one dispenser plus four cartridges per kit. First cartridge batch cost was 1.00 USD each.',
    '{"source":"user_cost_input","offer":"1_year_kit","cartridge_batch":"first_10000"}'
  ),
  (
    'trueclean',
    'product',
    'TrueClean 1-year kit - current cartridge cost',
    'active',
    20,
    null,
    null,
    '{}',
    '^TC-U-SNS-0[1-4]$|^TC-SNS-[A-Z]+-[1-4]$',
    null,
    null,
    null,
    null,
    null,
    4,
    2.50,
    0.65,
    0,
    null,
    '2026-05-03',
    null,
    'Old 1-year kit after the first 10k cartridges were consumed.',
    '{"source":"user_cost_input","offer":"1_year_kit","cartridge_batch":"current"}'
  ),
  (
    'trueclean',
    'product',
    'TrueClean 6-month kit - current cartridge cost',
    'active',
    10,
    null,
    null,
    '{}',
    '^TC-U-SNS-0[1-4]-N$|^TC-U-SNS-0[1-4]-RFL-01$',
    'Second TrueClean Unit',
    '6 Month|6 Months|6-Month',
    null,
    null,
    null,
    2,
    2.50,
    0.65,
    0,
    null,
    '2026-05-14',
    null,
    'Current 6-month kit: one dispenser plus two cartridges per kit. User approved 3.80 USD per kit from the switch date onward.',
    '{"source":"user_cost_input","offer":"6_month_kit","cartridge_batch":"current"}'
  ),
  (
    'trueclean',
    'product',
    'TrueClean 10-year refill supply - first 10k cartridge batch',
    'active',
    5,
    null,
    null,
    '{}',
    '^TC-RF-40$',
    '10-Year|10 Year',
    null,
    null,
    null,
    null,
    40,
    0,
    1.00,
    0,
    null,
    null,
    '2026-05-02',
    '10-year refill supply equals forty cartridges per unit. Shipping still needs its own refill-only rule once more actuals are available.',
    '{"source":"user_cost_input","offer":"10_year_refill","cartridge_batch":"first_10000","count_for_shipping":false}'
  ),
  (
    'trueclean',
    'product',
    'TrueClean 10-year refill supply - current cartridge cost',
    'active',
    5,
    null,
    null,
    '{}',
    '^TC-RF-40$',
    '10-Year|10 Year',
    null,
    null,
    null,
    null,
    40,
    0,
    0.65,
    0,
    null,
    '2026-05-03',
    null,
    '10-year refill supply equals forty cartridges per unit at the current 0.65 USD cartridge cost.',
    '{"source":"user_cost_input","offer":"10_year_refill","cartridge_batch":"current","count_for_shipping":false}'
  ),
  (
    'trueclean',
    'product',
    'TrueClean 4-refill cartridge pack - current cartridge cost',
    'active',
    6,
    null,
    null,
    '{}',
    '^TC-RF-4',
    'Refills',
    null,
    null,
    null,
    null,
    4,
    0,
    0.65,
    0,
    null,
    '2026-05-03',
    null,
    'Four cartridge refill pack at current cartridge cost.',
    '{"source":"user_cost_input","offer":"4_refill_pack","cartridge_batch":"current","count_for_shipping":false}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean US contiguous 1 kit',
    'active',
    10,
    'us_contiguous',
    'US',
    '{}',
    null,
    null,
    null,
    1,
    1,
    null,
    null,
    null,
    null,
    11.60,
    null,
    null,
    null,
    'Actual 1-year shipping sample averaged about 11.46 USD for one contiguous-US kit.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean US contiguous 2 kits',
    'active',
    10,
    'us_contiguous',
    'US',
    '{}',
    null,
    null,
    null,
    2,
    2,
    null,
    null,
    null,
    null,
    18.50,
    null,
    null,
    null,
    'Actual 1-year shipping sample averaged about 18.39 USD for two contiguous-US kits.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean US contiguous 3 kits',
    'active',
    10,
    'us_contiguous',
    'US',
    '{}',
    null,
    null,
    null,
    3,
    3,
    null,
    null,
    null,
    null,
    26.50,
    null,
    null,
    null,
    'Actual 1-year shipping sample averaged about 26.44 USD for three contiguous-US kits.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean US contiguous 4 kits',
    'active',
    10,
    'us_contiguous',
    'US',
    '{}',
    null,
    null,
    null,
    4,
    4,
    null,
    null,
    null,
    null,
    34.50,
    null,
    null,
    null,
    'Actual 1-year shipping sample averaged about 34.49 USD for four contiguous-US kits.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean US contiguous 5+ kits',
    'active',
    20,
    'us_contiguous',
    'US',
    '{}',
    null,
    null,
    null,
    5,
    null,
    null,
    null,
    null,
    null,
    34.50,
    7.90,
    null,
    null,
    'Actual sample showed 5+ kits were close to 34.50 plus 7.90 per kit above four.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders","base_kit_quantity":4}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean AK HI 2 kits',
    'active',
    5,
    'us_ak_hi',
    'US',
    '{"AK","HI"}',
    null,
    null,
    null,
    2,
    2,
    null,
    null,
    null,
    null,
    31.40,
    null,
    null,
    null,
    'Alaska and Hawaii used the island line in actuals and averaged about 31.41 USD for two-kit orders.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean Canada 2 kits',
    'active',
    10,
    'ca',
    'CA',
    '{}',
    null,
    null,
    null,
    2,
    2,
    null,
    null,
    null,
    null,
    17.70,
    null,
    null,
    null,
    'Actual Canada sample averaged about 17.68 USD for two-kit orders.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  ),
  (
    'trueclean',
    'shipping',
    'TrueClean Canada 4 kits',
    'active',
    10,
    'ca',
    'CA',
    '{}',
    null,
    null,
    null,
    4,
    4,
    null,
    null,
    null,
    null,
    32.80,
    null,
    null,
    null,
    'Actual Canada sample was 32.80 USD for the four-kit order.',
    '{"source":"actual_shipping_reconciliation","basis":"1_year_orders"}'
  )
on conflict (brand_slug, label) do update
set
  cost_type = excluded.cost_type,
  status = excluded.status,
  priority = excluded.priority,
  region_key = excluded.region_key,
  country_code = excluded.country_code,
  province_codes = excluded.province_codes,
  sku_pattern = excluded.sku_pattern,
  title_pattern = excluded.title_pattern,
  variant_pattern = excluded.variant_pattern,
  min_kit_quantity = excluded.min_kit_quantity,
  max_kit_quantity = excluded.max_kit_quantity,
  kit_multiplier = excluded.kit_multiplier,
  cartridges_per_kit = excluded.cartridges_per_kit,
  dispenser_unit_cost = excluded.dispenser_unit_cost,
  cartridge_unit_cost = excluded.cartridge_unit_cost,
  fixed_cost = excluded.fixed_cost,
  per_extra_kit_cost = excluded.per_extra_kit_cost,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  notes = excluded.notes,
  metadata = excluded.metadata,
  updated_at = now();
